### ISSUE TITLE
直接克隆仓库之后出现编译报错——缺少相关依赖包

### ISSUE THREAD

**Issue by HarveyJae** [ivaquero/book-control#1]
我已经安装好了typst这个软件，并且配置好了环境变量，当我克隆完仓库之后，编译"01-动态系统.typ"这个文件，但是出现了报错：
——————————————————————————————————————————————————————————
>    ┌─ E:\IOT\book-control\sci-book.typ:96:8
>    │
> 96 │ #import "../typst-packages/packages/preview/tablex/0.0.4/tablex.typ": *
>    │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>    │
>    = hint: cannot read file outside of project root
>    = hint: you can adjust the project root with the --root argument
> 
> help: error occurred while importing this module
>   ┌─ \E:\IOT\book-control\01-动态系统.typ:2:8
>   │
> 2 │ #import "sci-book.typ": *
>   │
——————————————————————————————————————————————————————————
上述报错的原因是我的文件夹中没有相应的table.typ这个包，当我注释掉#import "sci-book.typ"这句话之后，还会产生新的问题：
___________________________________________________________________________________________________________________________________________
>  E:\IOT\book-control>typst compile 01-动态系统.typ
>  error: unknown variable: thmrules
>    ┌─ \\?\E:\IOT\book-control\01-动态系统.typ:11:7
>    │
>  11 │ #show: thmrules
>    │
___________________________________________________________________________________________________________________________________________
是不是作者仓库中少上传了相关的依赖？希望能够得到解答

**Comment by ivaquero** [comment]
噢，我忘了把这个部分改一下了，稍等，我下午改一下

**Comment by ivaquero** [comment]
应该可以了

**Comment by HarveyJae** [comment]
万分感谢，已经解决！
